"""
因子函式庫 — 純函式，無狀態，可獨立測試。

每個因子：DataFrame → Series（因子值）

Sub-modules:
- technical: price/volume-based factors
- fundamental: financial statement-based factors
- kakushadze: selected Kakushadze 101 formulaic alphas
"""

__all__ = [
    # technical — original
    "momentum",
    "mean_reversion",
    "volatility",
    "rsi",
    "moving_average_crossover",
    "short_term_reversal",
    "amihud_illiquidity",
    "idiosyncratic_vol",
    "skewness",
    "max_return",
    "volume_price_trend",
    # technical — new indicators
    "bollinger_position",
    "macd_signal",
    "obv_trend",
    "adx",
    "cci",
    "williams_r",
    "stochastic_k",
    "atr_ratio",
    "price_acceleration",
    "volume_momentum",
    "high_low_range",
    "close_to_high",
    "gap_factor",
    "intraday_return",
    "overnight_return",
    # technical — academic factors
    "momentum_1m",
    "momentum_6m",
    "momentum_12m",
    "long_term_reversal",
    "beta_market",
    "idiosyncratic_skewness",
    "max_daily_return",
    "turnover_volatility",
    "price_delay",
    "zero_trading_days",
    # fundamental — original
    "value_pe",
    "value_pb",
    "quality_roe",
    "size_factor",
    "investment_factor",
    "gross_profitability_factor",
    # fundamental — Phase K3 new
    "revenue_yoy_factor",
    "revenue_momentum_factor",
    "revenue_new_high_factor",
    "revenue_acceleration_factor",
    "trust_cumulative_factor",
    "dividend_yield_factor",
    "foreign_net_factor",
    "trust_net_factor",
    "director_change_factor",
    "margin_change_factor",
    "daytrading_ratio_factor",
    # kakushadze helpers
    "_rank",
    "_ts_rank",
    "_decay_linear",
    "_ts_argmax",
    # kakushadze alphas
    "kakushadze_alpha_1",
    "kakushadze_alpha_2",
    "kakushadze_alpha_3",
    "kakushadze_alpha_4",
    "kakushadze_alpha_6",
    "kakushadze_alpha_7",
    "kakushadze_alpha_8",
    "kakushadze_alpha_9",
    "kakushadze_alpha_10",
    "kakushadze_alpha_12",
    "kakushadze_alpha_13",
    "kakushadze_alpha_14",
    "kakushadze_alpha_15",
    "kakushadze_alpha_16",
    "kakushadze_alpha_17",
    "kakushadze_alpha_18",
    "kakushadze_alpha_19",
    "kakushadze_alpha_20",
    "kakushadze_alpha_22",
    "kakushadze_alpha_23",
    "kakushadze_alpha_24",
    "kakushadze_alpha_30",
    "kakushadze_alpha_33",
    "kakushadze_alpha_34",
    "kakushadze_alpha_35",
    "kakushadze_alpha_38",
    "kakushadze_alpha_40",
    "kakushadze_alpha_44",
    "kakushadze_alpha_53",
    "kakushadze_alpha_101",
]

# Re-export all factors for backward compatibility
from src.strategy.factors.technical import (  # noqa: F401
    momentum,
    mean_reversion,
    volatility,
    rsi,
    moving_average_crossover,
    short_term_reversal,
    amihud_illiquidity,
    idiosyncratic_vol,
    skewness,
    max_return,
    volume_price_trend,
    bollinger_position,
    macd_signal,
    obv_trend,
    adx,
    cci,
    williams_r,
    stochastic_k,
    atr_ratio,
    price_acceleration,
    volume_momentum,
    high_low_range,
    close_to_high,
    gap_factor,
    intraday_return,
    overnight_return,
    momentum_1m,
    momentum_6m,
    momentum_12m,
    long_term_reversal,
    beta_market,
    idiosyncratic_skewness,
    max_daily_return,
    turnover_volatility,
    price_delay,
    zero_trading_days,
)
from src.strategy.factors.fundamental import (  # noqa: F401
    value_pe,
    value_pb,
    quality_roe,
    size_factor,
    investment_factor,
    gross_profitability_factor,
    revenue_yoy_factor,
    revenue_momentum_factor,
    revenue_new_high_factor,
    revenue_acceleration_factor,
    trust_cumulative_factor,
    dividend_yield_factor,
    foreign_net_factor,
    trust_net_factor,
    director_change_factor,
    margin_change_factor,
    daytrading_ratio_factor,
)
from src.strategy.factors.kakushadze import (  # noqa: F401
    _rank,
    _ts_rank,
    _decay_linear,
    _ts_argmax,
    kakushadze_alpha_1,
    kakushadze_alpha_2,
    kakushadze_alpha_3,
    kakushadze_alpha_4,
    kakushadze_alpha_6,
    kakushadze_alpha_7,
    kakushadze_alpha_8,
    kakushadze_alpha_9,
    kakushadze_alpha_10,
    kakushadze_alpha_12,
    kakushadze_alpha_13,
    kakushadze_alpha_14,
    kakushadze_alpha_15,
    kakushadze_alpha_16,
    kakushadze_alpha_17,
    kakushadze_alpha_18,
    kakushadze_alpha_19,
    kakushadze_alpha_20,
    kakushadze_alpha_22,
    kakushadze_alpha_23,
    kakushadze_alpha_24,
    kakushadze_alpha_30,
    kakushadze_alpha_33,
    kakushadze_alpha_34,
    kakushadze_alpha_35,
    kakushadze_alpha_38,
    kakushadze_alpha_40,
    kakushadze_alpha_44,
    kakushadze_alpha_53,
    kakushadze_alpha_101,
)
