export { isAuthenticated, login, logout, ApiError, get, post, put, del } from "./client";
export {
  WSManager,
  auth as authEndpoints,
  backtest as backtestEndpoints,
  strategies as strategiesEndpoints,
  system as systemEndpoints,
  risk as riskEndpoints,
  portfolio as portfolioEndpoints,
  alpha as alphaEndpoints,
  pollBacktestResult,
} from "@quant/shared";
export type { Channel } from "@quant/shared";
export type {
  BacktestRequest,
  BacktestSummary,
  BacktestResult,
  ManualOrderRequest,
  NavPoint,
  OrderInfo,
  Portfolio,
  Position,
  RiskAlert,
  RiskRule,
  StrategyInfo,
  TradeRecord,
  UserInfo,
  UserRole,
  AlphaRunRequest,
  AlphaSummary,
  AlphaReport,
  AlphaFactorSpec,
  FactorReport,
  ICResult,
  QuantileReturn,
} from "@quant/shared";
