@echo off
REM Auto-generated by scripts/autostart.py
REM Daily backup of critical trading data

echo [%date% %time%] Starting daily backup... >> "D:\Finance\data\autostart.log"
cd /d "D:\Finance"
"C:\Users\ander\AppData\Local\Programs\Python\Python312\python.exe" scripts/autostart.py _backup
echo [%date% %time%] Backup complete. >> "D:\Finance\data\autostart.log"
