@echo off
REM Auto-generated by scripts/autostart.py
REM Start API server if not already running

netstat -ano 2>NUL | find ":8000" | find "LISTENING" >NUL
if %ERRORLEVEL%==0 (
    echo [%date% %time%] Server already running, skipping. >> "D:\Finance\data\autostart.log"
    exit /b 0
)

echo [%date% %time%] Starting API server... >> "D:\Finance\data\autostart.log"
cd /d "D:\Finance"
start "QuantServer" /MIN "C:\Users\ander\AppData\Local\Programs\Python\Python312\python.exe" -m src.cli.main server
