@echo off
REM Auto-generated by scripts/autostart.py
REM Run silence watchdog during market hours, auto-exit after 13:35

tasklist /FI "WINDOWTITLE eq QuantWatchdog" 2>NUL | find /I "python" >NUL
if %ERRORLEVEL%==0 (
    echo [%date% %time%] Watchdog already running, skipping. >> "D:\Finance\data\autostart.log"
    exit /b 0
)

echo [%date% %time%] Starting silence watchdog... >> "D:\Finance\data\autostart.log"
cd /d "D:\Finance"
start "QuantWatchdog" /MIN "C:\Users\ander\AppData\Local\Programs\Python\Python312\python.exe" scripts/silence_watchdog.py --loop --interval 300 --stop-after 270
