"""Register / unregister Windows Task Scheduler tasks for auto-start.

Tasks created:
  1. Quant_Server_PreMarket  — daily 07:45, starts API server before market open
  2. Quant_Server_OnLogon    — on user logon, starts API server after reboot
  3. Quant_Watchdog_Market   — daily 09:05, silence watchdog during market hours
  4. Quant_Backup_Daily      — daily 14:00, backup critical trading data

All tasks check for duplicates before starting.

Usage:
  python scripts/autostart.py install   # register all tasks
  python scripts/autostart.py uninstall # remove all tasks
  python scripts/autostart.py status    # show current task status
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

PROJECT_DIR = Path(__file__).resolve().parent.parent
PYTHON_EXE = sys.executable
SCRIPTS_DIR = PROJECT_DIR / "scripts"

# All launcher .bat files generated by this script
LAUNCHERS: dict[str, Path] = {
    "server": SCRIPTS_DIR / "_launch_server.bat",
    "watchdog": SCRIPTS_DIR / "_launch_watchdog.bat",
    "backup": SCRIPTS_DIR / "_launch_backup.bat",
}

TASKS = {
    "Quant_Server_PreMarket": {
        "trigger": "/sc DAILY /st 07:45",
        "launcher": "server",
        "desc": "Start API server at 07:45 (pre-market)",
    },
    "Quant_Server_OnLogon": {
        "trigger": "/sc ONLOGON /delay 0000:30",
        "launcher": "server",
        "desc": "Start API server on user logon (30s delay)",
    },
    "Quant_Watchdog_Market": {
        "trigger": "/sc DAILY /st 09:05",
        "launcher": "watchdog",
        "desc": "Silence watchdog during market hours (09:05-13:35)",
    },
    "Quant_Backup_Daily": {
        "trigger": "/sc DAILY /st 14:00",
        "launcher": "backup",
        "desc": "Backup trading data after market close (14:00)",
    },
}

# Backup source directories/files (relative to PROJECT_DIR)
BACKUP_SOURCES = [
    "data/paper_trading",       # portfolio state, NAV history
    "data/smoke_test",          # smoke test results
    "data/paper_vs_backtest",   # consistency reports
    "data/trade_ledger",        # all trade records
]


def _write_launchers() -> None:
    """Write all .bat launcher scripts."""

    # --- Server launcher ---
    LAUNCHERS["server"].write_text(f"""@echo off
REM Auto-generated by scripts/autostart.py
REM Start API server if not already running

netstat -ano 2>NUL | find ":8000" | find "LISTENING" >NUL
if %ERRORLEVEL%==0 (
    echo [%date% %time%] Server already running, skipping. >> "{PROJECT_DIR}\\data\\autostart.log"
    exit /b 0
)

echo [%date% %time%] Starting API server... >> "{PROJECT_DIR}\\data\\autostart.log"
cd /d "{PROJECT_DIR}"
start "QuantServer" /MIN "{PYTHON_EXE}" -m src.cli.main server
""", encoding="utf-8")

    # --- Watchdog launcher ---
    # Runs silence_watchdog in loop mode, exits after market close (13:35)
    LAUNCHERS["watchdog"].write_text(f"""@echo off
REM Auto-generated by scripts/autostart.py
REM Run silence watchdog during market hours, auto-exit after 13:35

tasklist /FI "WINDOWTITLE eq QuantWatchdog" 2>NUL | find /I "python" >NUL
if %ERRORLEVEL%==0 (
    echo [%date% %time%] Watchdog already running, skipping. >> "{PROJECT_DIR}\\data\\autostart.log"
    exit /b 0
)

echo [%date% %time%] Starting silence watchdog... >> "{PROJECT_DIR}\\data\\autostart.log"
cd /d "{PROJECT_DIR}"
start "QuantWatchdog" /MIN "{PYTHON_EXE}" scripts/silence_watchdog.py --loop --interval 300 --stop-after 270
""", encoding="utf-8")

    # --- Backup launcher ---
    LAUNCHERS["backup"].write_text(f"""@echo off
REM Auto-generated by scripts/autostart.py
REM Daily backup of critical trading data

echo [%date% %time%] Starting daily backup... >> "{PROJECT_DIR}\\data\\autostart.log"
cd /d "{PROJECT_DIR}"
"{PYTHON_EXE}" scripts/autostart.py _backup
echo [%date% %time%] Backup complete. >> "{PROJECT_DIR}\\data\\autostart.log"
""", encoding="utf-8")

    for name, path in LAUNCHERS.items():
        print(f"  Launcher: {path.name}")


def _run_schtasks(args: str) -> subprocess.CompletedProcess:
    return subprocess.run(f"schtasks {args}", shell=True, capture_output=True, text=True)


def install() -> None:
    """Register all scheduled tasks."""
    _write_launchers()
    print()

    for name, cfg in TASKS.items():
        _run_schtasks(f"/delete /tn {name} /f")
        launcher = LAUNCHERS[cfg["launcher"]]
        cmd = (
            f'/create /tn {name} {cfg["trigger"]} '
            f'/tr "\"{launcher}\"" '
            f'/rl HIGHEST /f'
        )
        result = _run_schtasks(cmd)
        if result.returncode == 0:
            print(f"  [OK] {name} — {cfg['desc']}")
        else:
            print(f"  [FAIL] {name} — {result.stderr.strip()}")

    # Clean up old task names (migration)
    for old in ("QuantServer_PreMarket", "QuantServer_OnLogon"):
        _run_schtasks(f"/delete /tn {old} /f")
    old_launcher = SCRIPTS_DIR / "_autostart_launcher.bat"
    if old_launcher.exists():
        old_launcher.unlink()

    print()
    print("Scheduled tasks installed:")
    print("  07:45        API server start (+ on logon)")
    print("  09:05-13:35  Silence watchdog (5 min interval)")
    print("  14:00        Daily backup")
    print()
    print("To remove: python scripts/autostart.py uninstall")


def uninstall() -> None:
    """Remove all scheduled tasks and launchers."""
    for name in TASKS:
        result = _run_schtasks(f"/delete /tn {name} /f")
        if result.returncode == 0:
            print(f"  [OK] Removed {name}")
        else:
            print(f"  [--] {name} not found")

    for path in LAUNCHERS.values():
        if path.exists():
            path.unlink()
            print(f"  [OK] Removed {path.name}")

    print("\nAll auto-start tasks uninstalled.")


def status() -> None:
    """Show current task status."""
    found = False
    for name, cfg in TASKS.items():
        result = _run_schtasks(f"/query /tn {name} /fo LIST /v")
        if result.returncode == 0:
            found = True
            info = {}
            for line in result.stdout.strip().split("\n"):
                if ":" in line:
                    key, _, val = line.partition(":")
                    info[key.strip()] = val.strip()
            print(f"  {name} ({cfg['desc']}):")
            print(f"    Status:      {info.get('Status', '?')}")
            print(f"    Next run:    {info.get('Next Run Time', '?')}")
            print(f"    Last run:    {info.get('Last Run Time', 'Never')}")
            print(f"    Last result: {info.get('Last Result', 'N/A')}")
            print()

    if not found:
        print("  No scheduled tasks registered.")
        print("  Run: python scripts/autostart.py install")


def run_backup() -> None:
    """Execute backup of critical trading data."""
    import shutil
    from datetime import datetime, timedelta, timezone

    tw = timezone(timedelta(hours=8))
    today = datetime.now(tw).strftime("%Y-%m-%d")
    backup_root = PROJECT_DIR / "data" / "backups" / today

    if backup_root.exists():
        print(f"  Backup for {today} already exists, skipping.")
        return

    copied = 0
    for rel in BACKUP_SOURCES:
        src = PROJECT_DIR / rel
        if not src.exists():
            continue
        dst = backup_root / rel
        if src.is_dir():
            shutil.copytree(src, dst)
        else:
            dst.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, dst)
        copied += 1
        print(f"  [OK] {rel}")

    if copied == 0:
        print("  No data to backup yet.")
        return

    # Prune old backups (keep 30 days)
    backup_parent = PROJECT_DIR / "data" / "backups"
    all_backups = sorted(d for d in backup_parent.iterdir() if d.is_dir())
    if len(all_backups) > 30:
        for old in all_backups[:-30]:
            shutil.rmtree(old)
            print(f"  [pruned] {old.name}")

    print(f"\n  Backup complete: {backup_root}")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python scripts/autostart.py [install|uninstall|status]")
        sys.exit(1)

    action = sys.argv[1]

    if action == "_backup":
        run_backup()
    elif action in ("install", "uninstall", "status"):
        print(f"\n=== Quant Auto-Start: {action} ===\n")
        {"install": install, "uninstall": uninstall, "status": status}[action]()
    else:
        print("Usage: python scripts/autostart.py [install|uninstall|status]")
        sys.exit(1)
