# Autoresearch Status Report Generator
# Usage: powershell -File scripts/autoresearch/status.ps1
# Output: docs/research/autoresearch-status.md (auto-overwrite)

$WorkDir = "D:\Finance\docker\autoresearch\work"
$OutFile = "D:\Finance\docs\research\autoresearch\status.md"
$Now = Get-Date -Format "yyyy-MM-dd HH:mm:ss"

# --- Gather data ---

# Container status
$agentUp = docker ps --filter "name=autoresearch-agent" --format "{{.Status}}" 2>$null
$watchdogUp = docker ps --filter "name=autoresearch-watchdog" --format "{{.Status}}" 2>$null
if (-not $agentUp) { $agentUp = "STOPPED" }
if (-not $watchdogUp) { $watchdogUp = "STOPPED" }

# Results
$results = @()
$bestScore = 0
$bestFactor = "N/A"
$totalExperiments = 0
$keepCount = 0
$discardCount = 0
$l5Count = 0

if (Test-Path "$WorkDir\results.tsv") {
    $lines = Get-Content "$WorkDir\results.tsv" | Select-Object -Skip 1 | Where-Object { $_.Trim() -ne "" }
    $totalExperiments = $lines.Count
    foreach ($line in $lines) {
        $cols = $line -split "`t"
        if ($cols.Count -ge 6) {
            $score = [double]$cols[1]
            $icir = $cols[2]
            $level = $cols[3]
            $status = $cols[4]
            $desc = $cols[5]
            if ($status -eq "keep") { $keepCount++ }
            if ($status -eq "discard") { $discardCount++ }
            if ($level -eq "L5") { $l5Count++ }
            if ($score -gt $bestScore) {
                $bestScore = $score
                $bestFactor = $desc
            }
            $results += [PSCustomObject]@{
                Score = $score; ICIR = $icir; Level = $level; Status = $status; Desc = $desc
            }
        }
    }
}

# Recent watchdog alerts (non-__pycache__)
$alerts = docker logs autoresearch-watchdog --tail 100 2>&1 |
    Where-Object { $_ -match "ALERT|STALE|crashed" } |
    Select-Object -Last 5

# Git log
$gitLog = git -C $WorkDir log --oneline -10 2>$null

# --- Generate report ---

$report = @"
# Autoresearch Status Report

> Updated: $Now

## Dashboard

| Item | Value |
|------|-------|
| Agent container | $agentUp |
| Watchdog container | $watchdogUp |
| Total experiments | $totalExperiments |
| Keep / Discard | $keepCount / $discardCount |
| L5 OOS passed | $l5Count |
| Best score | $bestScore |
| Best factor | $bestFactor |

## Experiment Log (latest first)

| Score | ICIR | Level | Status | Description |
|------:|-----:|-------|--------|-------------|
"@

# Add rows in reverse order (latest first)
for ($i = $results.Count - 1; $i -ge 0; $i--) {
    $r = $results[$i]
    $report += "| $($r.Score) | $($r.ICIR) | $($r.Level) | $($r.Status) | $($r.Desc) |`n"
}

$report += @"

## Recent Alerts

"@

if ($alerts) {
    foreach ($a in $alerts) {
        $report += "- ``$a```n"
    }
} else {
    $report += "None`n"
}

$report += @"

## Recent Commits

``````
$($gitLog -join "`n")
``````

---
*Auto-generated by ``scripts/autoresearch/status.ps1``*
"@

# --- Write ---
$report | Out-File -Encoding utf8 $OutFile
Write-Host "Status report written to: $OutFile" -ForegroundColor Green
